page_id   = 12345678
target_path = "~/rust_output/"
prodwares = [
  "advancedcomposites",
  "advancedelectronics",
  "antimattercells",
  "antimatterconverters",
  "claytronics",
  "dronecomponents",
  "energycells",
  "engineparts",
  "fieldcoils",
  "foodrations",
  "graphene",
  "hullparts",
  "majadust",
  "majasnails",
  "meat",
  "medicalsupplies",
  "microchips",
  "missilecomponents",
  "nostropoil",
  "plasmaconductors",
  "quantumtubes",
  "refinedmetals",
  "scanningarrays",
  "shieldcomponents",
  "siliconwafers",
  "smartchips",
  "sojabeans",
  "sojahusk",
  "spacefuel",
  "spaceweed",
  "spices",
  "sunriseflowers",
  "superfluidcoolant",
  "swampplant",
  "teladianium",
  "turretcomponents",
  "water",
  "weaponcomponents",
  "wheat",
]
factions = [
  "khaakpox",
  "xenonmatrix",
  "atlas",
  "sovsyn",
  "cartel",
  "agi",
  "goner",
  "wholefood",
  "ledda",
  "telunion",
  "aldrin",
  "cantera",
  "toride",
  "nmmc",
  "atreus",
  "jonferson",
  "aquariuscorp",
  "ptni",
  "strongarms",
  "plutarch",
  "albionenergy",
  "terracorp",
  "franton",
  "chow",
  "beryll",
  "terrapmc",
  "otas",
  "buccaneers",
  "reivers",
  "terrans",
  "nolimits",
  "uguras",
  "heretics",
  "yaki",
  "usc",
  "heartofalbion",
  "sonraenergy",
]

[general_modifiers]
weak      = ["Rusty ", "Weak ", "Damaged ", "Diminished ","Fragile ", "Flawed ", "Impulse ",]
strong    = ["Advanced ", "Phased ", "Array ", "Fragmentation "]
gun_type   = ["Particle ", "Plasma ", "Ion ", "Artillery ", "Concussion "]
gun_method = ["Launcher ", "Driver ", "Railgun ", "Emitter ", "Ray ", "Cannon ", "Generator ", "Projector ", ]
[art]
icons = [
  "bullet_arg_s_ion_01_mk1",      "bullet_arg_s_ion_01_mk2",
  "bullet_gen_s_gatling_01_mk1",  "bullet_gen_s_gatling_01_mk2",
  "bullet_gen_s_laser_01_mk1",    "bullet_gen_s_laser_01_mk2",
  "bullet_gen_s_plasma_01_mk1",   "bullet_gen_s_plasma_01_mk2",
  "bullet_gen_s_shotgun_01_mk1",  "bullet_gen_s_shotgun_01_mk2",
  "bullet_gen_s_gatling_01_mk1",
  "bullet_gen_s_laser_01_mk1",
  "bullet_gen_s_plasma_01_mk1",
  "bullet_gen_s_shotgun_01_mk1",
  "bullet_par_s_railgun_01_mk1",  "bullet_par_s_railgun_01_mk2",
  "bullet_tel_s_charge_01_mk1",   "bullet_tel_s_charge_01_mk2",
  "bullet_xen_s_laser_01_mk1",    "bullet_xen_s_laser_01_mk1",
]
[art.effects]
impact = [
  # xs
  "impact_gen_spacesuit_laser_01_mk1",
  "impact_spacesuit_repair_01_mk1",

  # s
  "impact_arg_s_ion_01_mk1",    "impact_arg_s_ion_01_mk1",
  "impact_gen_s_beam_01_mk1",   "impact_gen_s_beam_01_mk1",   "impact_gen_s_beam_01_mk1",
  "impact_gen_s_gatling_01_mk1","impact_gen_s_gatling_01_mk1","impact_gen_s_gatling_01_mk1",
  "impact_gen_s_laser_01_mk1",  "impact_gen_s_laser_01_mk1",  "impact_gen_s_laser_01_mk1",
  "impact_gen_s_plasma_01_mk1", "impact_gen_s_plasma_01_mk1", "impact_gen_s_plasma_01_mk1",
  "impact_gen_s_shotgun_01_mk1","impact_gen_s_shotgun_01_mk1","impact_gen_s_shotgun_01_mk1",
  "impact_par_s_railgun_01_mk1","impact_par_s_railgun_01_mk1",
  "impact_tel_s_charge_01_mk1", "impact_tel_s_charge_01_mk1",
  "impact_xen_s_laser_01_mk1",  "impact_xen_s_laser_01_mk1",

  # m
  "impact_arg_m_ion_01_mk1",    "impact_arg_m_ion_01_mk1",
  "impact_gen_m_beam_01_mk1",   "impact_gen_m_beam_01_mk1",   "impact_gen_m_beam_01_mk1",
  "impact_gen_m_beam_01_mk1",   "impact_gen_m_beam_01_mk1",
  "impact_gen_m_gatling_01_mk1","impact_gen_m_gatling_01_mk1","impact_gen_m_gatling_01_mk1",
  "impact_gen_m_laser_01_mk1",  "impact_gen_m_laser_01_mk1",  "impact_gen_m_laser_01_mk1",
  "impact_gen_m_plasma_01_mk1", "impact_gen_m_plasma_01_mk1", "impact_gen_m_plasma_01_mk1",
  "impact_gen_m_shotgun_01_mk1","impact_gen_m_shotgun_01_mk1","impact_gen_m_shotgun_01_mk1",
  "impact_par_m_railgun_01_mk1","impact_par_m_railgun_01_mk1",
  "impact_tel_m_charge_01_mk1", "impact_tel_m_charge_01_mk1",
  "impact_xen_m_laser_01_mk1",  "impact_xen_m_laser_01_mk1",  "impact_xen_m_laser_01_mk1",

  # l
  "impact_gen_l_laser_01_mk1",
]
muzzle = [
  # ???
  "wpn_flare_launcher",
  # xs?
  "muzzle_gen_spacesuit_laser_01_mk1",
  "muzzle_gen_s_repair_01_mk1",

  # s
  "muzzle_arg_s_ion_01_mk1",    "muzzle_arg_s_ion_01_mk1",
  "muzzle_gen_s_beam_01_mk1",   "muzzle_gen_s_beam_01_mk1",   "muzzle_gen_s_beam_01_mk1",
  "muzzle_gen_s_gatling_01_mk1","muzzle_gen_s_gatling_01_mk1","muzzle_gen_s_gatling_01_mk1",
  "muzzle_gen_s_laser_01_mk1",  "muzzle_gen_s_laser_01_mk1",  "muzzle_gen_s_laser_01_mk1",
  "muzzle_gen_s_plasma_01_mk1", "muzzle_gen_s_plasma_01_mk1", "muzzle_gen_s_plasma_01_mk1",
  "muzzle_gen_s_shotgun_01_mk1","muzzle_gen_s_shotgun_01_mk1","muzzle_gen_s_shotgun_01_mk1",
  "muzzle_par_s_railgun_01_mk1","muzzle_par_s_railgun_01_mk1",
  "muzzle_tel_s_charge_01_mk1", "muzzle_tel_s_charge_01_mk1",
  "muzzle_xen_s_laser_01_mk1",  "muzzle_xen_s_laser_01_mk1",

  # m
  "muzzle_arg_m_ion_01_mk1",    "muzzle_arg_m_ion_01_mk1",
  "muzzle_gen_m_beam_01_mk1",   "muzzle_gen_m_beam_01_mk1",   "muzzle_gen_m_beam_01_mk1",   "muzzle_gen_m_beam_01_mk1",
  "muzzle_gen_m_gatling_01_mk1","muzzle_gen_m_gatling_01_mk1","muzzle_gen_m_gatling_01_mk1",
  "muzzle_gen_m_laser_01_mk1",  "muzzle_gen_m_laser_01_mk1",  "muzzle_gen_m_laser_01_mk1",
  "muzzle_gen_m_plasma_01_mk1", "muzzle_gen_m_plasma_01_mk1", "muzzle_gen_m_plasma_01_mk1",
  "muzzle_gen_m_shotgun_01_mk1","muzzle_gen_m_shotgun_01_mk1","muzzle_gen_m_shotgun_01_mk1",
  "muzzle_par_m_railgun_01_mk1","muzzle_par_m_railgun_01_mk1",
  "muzzle_tel_m_charge_01_mk1", "muzzle_tel_m_charge_01_mk1",
  "muzzle_xen_m_laser_01_mk1",  "muzzle_xen_m_laser_01_mk1",  "muzzle_xen_m_laser_01_mk1",

  # l
  "muzzle_gen_l_beam_01_mk1",
  "muzzle_gen_l_laser_01_mk1",
]

[size.Small]
# Limits
weapon_range = [2,10]
rate_of_fire=[0.5,5.0]
damage_min=[10,50]
damage_max=[50,100]
speed = [500, 2000]
rot_max = [10,240]
rot_accel = [10, 240]
reload_time=[1, 10]
hull_value = [500, 2000]
damage_flat_max=101
# Other parameters
modifiers=["Alpha ", "Small ", "75mm ", "100mm ", "Light ", "Tiny ", "limited ",] # TODO capital L on limited??
weapon_art = [
  "weapon_arg_s_ion_01_mk1",  "weapon_arg_s_ion_01_mk2",
  "weapon_gen_s_beam_01_mk1",  "weapon_gen_s_beam_01_mk2",
  "weapon_gen_s_gatling_01_mk1",  "weapon_gen_s_gatling_01_mk2",
  "weapon_gen_s_plasma_01_mk1",  "weapon_gen_s_plasma_01_mk2",
  "weapon_par_s_railgun_01_mk1",  "weapon_par_s_railgun_01_mk2",
  "weapon_tel_s_charge_01_mk1",  "weapon_tel_s_charge_01_mk2",
  "weapon_gen_s_laser_01_mk1",  "weapon_gen_s_laser_01_mk2",  "weapon_kha_s_laser_01_mk1",  "weapon_xen_s_laser_01_mk1",
  "weapon_gen_s_shotgun_01_mk1",  "weapon_gen_s_shotgun_01_mk2",
]
beams = [
  "bullet_gen_s_beam_01_mk1",  "bullet_gen_s_beam_01_mk2",
  "bullet_gen_s_beam_01_mk1",  "bullet_kha_s_beam_01",
]
projectiles = [
  "bullet_arg_s_ion_01_mk1",      "bullet_arg_s_ion_01_mk2",
  "bullet_gen_s_gatling_01_mk1",  "bullet_gen_s_gatling_01_mk2",
  "bullet_gen_s_laser_01_mk1",    "bullet_gen_s_laser_01_mk2",
  "bullet_gen_s_plasma_01_mk1",   "bullet_gen_s_plasma_01_mk2",
  "bullet_gen_s_shotgun_01_mk1",  "bullet_gen_s_shotgun_01_mk2",
  "bullet_gen_s_gatling_01_mk1",
  "bullet_gen_s_laser_01_mk1",
  "bullet_gen_s_plasma_01_mk1",
  "bullet_gen_s_shotgun_01_mk1",
  "bullet_par_s_railgun_01_mk1",  "bullet_par_s_railgun_01_mk2",
  "bullet_tel_s_charge_01_mk1",   "bullet_tel_s_charge_01_mk2",
  "bullet_xen_s_laser_01_mk1",    "bullet_xen_s_laser_01_mk1",
]


[size.Medium]
weapon_range = [4,10]
rate_of_fire=[0.5,5.0]
damage_min=[10,50]
damage_max=[50,100]
speed = [500, 2000]
rot_max = [10,240]
rot_accel = [10, 240]
reload_time=[1, 10]
hull_value = [500, 2000]
damage_flat_max=101
modifiers=["150mm ", "200mm ", "Medium ", "Standard ", "Beta ",]
weapon_art = [
  "weapon_arg_m_ion_01_mk1",  "weapon_arg_m_ion_01_mk2",
  "weapon_gen_m_beam_01_mk1",  "weapon_gen_m_beam_01_mk2",
  "weapon_gen_m_gatling_01_mk1",  "weapon_gen_m_gatling_01_mk2",
  "weapon_gen_m_plasma_01_mk1",  "weapon_gen_m_plasma_01_mk2",
  "weapon_par_m_railgun_01_mk1",  "weapon_par_m_railgun_01_mk2",
  "weapon_tel_m_charge_01_mk1",  "weapon_tel_m_charge_01_mk2",
  "weapon_gen_m_laser_01_mk1",  "weapon_gen_m_laser_01_mk2",
  "weapon_gen_m_shotgun_01_mk1",  "weapon_gen_m_shotgun_01_mk2",
  "weapon_kha_m_laser_01_mk1",  "weapon_xen_m_laser_01_mk1"
]
turret_art= [
  "turret_arg_m_beam_01_mk1",  "turret_arg_m_beam_02_mk1",
  "turret_par_m_beam_01_mk1",  "turret_par_m_beam_02_mk1",
  "turret_tel_m_beam_01_mk1",  "turret_tel_m_beam_02_mk1",
  "turret_arg_m_gatling_01_mk1",  "turret_arg_m_gatling_02_mk1",
  "turret_arg_m_plasma_01_mk1",  "turret_arg_m_plasma_02_mk1",
  "turret_kha_m_beam_01_mk1",
  "turret_par_m_gatling_01_mk1",  "turret_par_m_gatling_02_mk1",
  "turret_par_m_plasma_01_mk1",  "turret_par_m_plasma_02_mk1",
  "turret_tel_m_gatling_01_mk1",  "turret_tel_m_gatling_02_mk1",
  "turret_tel_m_plasma_01_mk1",  "turret_tel_m_plasma_02_mk1",
  "turret_arg_m_laser_01_mk1",  "turret_arg_m_laser_02_mk1",
  "turret_arg_m_shotgun_01_mk1",  "turret_arg_m_shotgun_02_mk1",
  "turret_par_m_laser_01_mk1",  "turret_par_m_laser_02_mk1",
    "turret_par_m_shotgun_01_mk1",  "turret_par_m_shotgun_02_mk1",
    "turret_tel_m_laser_01_mk1",  "turret_tel_m_laser_02_mk1",
    "turret_tel_m_shotgun_01_mk1",  "turret_tel_m_shotgun_02_mk1",
    "turret_xen_m_laser_02_mk1",  "turret_xen_m_laser_01_mk1",  "turret_xen_m_laser_02_mk1",
]
beams = [
  "bullet_gen_m_beam_01_mk1",
  "bullet_gen_m_beam_01_mk2",
  "bullet_gen_m_beam_01_mk1",
  "bullet_kha_m_beam_01",
  "bullet_gen_m_beam_01_mk1",  ]

projectiles = [
  "bullet_arg_m_ion_01_mk1",      "bullet_arg_m_ion_01_mk2",
  "bullet_gen_m_gatling_01_mk1",  "bullet_gen_m_gatling_01_mk2",
  "bullet_gen_m_laser_01_mk1",    "bullet_gen_m_laser_01_mk2",
  "bullet_gen_m_plasma_01_mk1",   "bullet_gen_m_plasma_01_mk2",
  "bullet_gen_m_shotgun_01_mk1",  "bullet_gen_m_shotgun_01_mk2",
  "bullet_gen_m_gatling_01_mk1",
  "bullet_gen_m_laser_01_mk1",
  "bullet_gen_m_plasma_01_mk1",
  "bullet_gen_m_shotgun_01_mk1",
  "bullet_par_m_railgun_01_mk1",  "bullet_par_m_railgun_01_mk2",
  "bullet_tel_m_charge_01_mk1",   "bullet_tel_m_charge_01_mk2",
  "bullet_xen_m_laser_01_mk1",    "bullet_xen_m_laser_01_mk1",
]


[size.Large]
weapon_range = [6, 12]
rate_of_fire=[0.5,5.0]
damage_min=[10,50]
damage_max=[50,100]
speed = [500, 2000]
rot_max = [10,240]
rot_accel = [10, 240]
reload_time=[1, 10]
hull_value = [500, 2000]
damage_flat_max=101
modifiers = ["300mm ", "400mm ", "Large ", "Gamma ", "Heavy ",]
weapon_art = [
  "weapon_arg_l_destroyer_01_mk1",
  "weapon_par_l_destroyer_01_mk1",
  "weapon_tel_l_destroyer_01_mk1",
  "weapon_arg_l_plasma_01_mk1",
  "weapon_par_l_railgun_01_mk1",
  "weapon_tel_l_beam_01_mk1",
  "weapon_gen_l_laser_01_mk1",
]
turret_art= [
  "turret_arg_l_beam_01_mk1",   "turret_par_l_beam_01_mk1",   "turret_tel_l_beam_01_mk1",
  "turret_arg_l_plasma_01_mk1", "turret_par_l_plasma_01_mk1", "turret_tel_l_plasma_01_mk1",
  "turret_arg_l_laser_01_mk1",  "turret_par_l_laser_01_mk1",  "turret_tel_l_laser_01_mk1",  "turret_xen_l_laser_01_mk1",
]
beams = [] # TODO should this be empty?
projectiles = [
  "bullet_gen_l_laser_01_mk1",
  "bullet_xen_l_laser_01_mk1"
]

[size.ExtraLarge]
# TODO any extra large ones?
weapon_range = [8,14]
rate_of_fire=[10.0,50.0]
damage_min=[1000,5000]
damage_max=[5000,50000]
speed = [500, 2000]
rot_max = [10,240]
rot_accel = [10, 240]
reload_time=[1, 10]
hull_value = [500, 2000]
damage_flat_max=50001

modifiers = ["300mm ", "400mm ", "Large ", "Gamma ", "Heavy ",]
# TODO any extra large ones?
weapon_art = [
  "weapon_arg_l_destroyer_01_mk1",
  "weapon_par_l_destroyer_01_mk1",
  "weapon_tel_l_destroyer_01_mk1",
  "weapon_arg_l_plasma_01_mk1",
  "weapon_par_l_railgun_01_mk1",
  "weapon_tel_l_beam_01_mk1",
  "weapon_gen_l_laser_01_mk1",
]
turret_art= [
  "turret_arg_l_beam_01_mk1",   "turret_par_l_beam_01_mk1",   "turret_tel_l_beam_01_mk1",
  "turret_arg_l_plasma_01_mk1", "turret_par_l_plasma_01_mk1", "turret_tel_l_plasma_01_mk1",
  "turret_arg_l_laser_01_mk1",  "turret_par_l_laser_01_mk1",  "turret_tel_l_laser_01_mk1",  "turret_xen_l_laser_01_mk1",
]
beams = [] # TODO should this be empty?
projectiles = [
  "bullet_gen_l_laser_01_mk1",
  "bullet_xen_l_laser_01_mk1"
]